version: "3"
# Docker Networks
networks:
  laravel:
    driver: bridge
# Docker Services
services:
  # PHP Service
  app:
    container_name: php-app
    build:
      context: .
      dockerfile: app.dockerfile
    image: php-app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - laravel
    depends_on:
      - db
  # Nginx Service
  nginx:
    container_name: nginx
    image: nginx:alpine
    # restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    tty: true
    ports:
      - "80:80"
    networks:
      - laravel
    depends_on:
      - db
  # Mysql Service
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    networks:
      - laravel

